# Generated by Django 5.0.7 on 2024-07-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_users', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
