# Generated by Django 5.0.7 on 2024-07-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_system', '0002_alter_users_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='id_users',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
